export const ADD_SENTIMENT = "ADD_SENTIMENT";
export const REMOVE_SENTIMENT = "REMOVE_SENTIMENT";
export const UPDATE_SENTIMENT = "UPDATE_SENTIMENT";

export const ADD_SENTENCE = "ADD_SENTENCE";
export const REMOVE_SENTENCE = "REMOVE_SENTENCE";
export const UPDATE_SENTENCE = "UPDATE_SENTENCE";
export const TRAINING_START = "TRAINING_START";
export const TRAINING_END = "TRAINING_END";

